### ISSUE TITLE
Titles of entries containing quote signs got broken due to the podcast generator update

### ISSUE THREAD

**Issue by joerg-nafcom** [PodcastGenerator/PodcastGenerator#210]
Titles of entries containing quote signs got broken due to the podcast generator update

E.g. Birgit "Biggi" Lechtermann (English Version) - Interview #58 

is defaced to
```
Birgit &quot;Biggi&quot; Lechtermann (English Version) - Interview #58
```
Even the bugfix release of 3.0.1 did not fix this.

**Comment by joerg-nafcom** [comment]
Unfortunately the rebuilding process of the 3.0.1 while fixing the broken RSS issue, now also wrote the defaced titles in the RSS feed :( as seen here: http://feeds.feedburner.com/SceneWorldTechHistoryInterviews

**Comment by emilengler** [comment]
Can you disable that feedburner puts the title into `CDATA` tags?
If you access your plain feed.xml, you shouldn't see this right?

**Comment by joerg-nafcom** [comment]
Nope, the problem is originated in the plain feed.xml too as well as the CDATA is generated from Podcast Generator too. 
See https://sceneworld.org/history/feed.xml

**Comment by emilengler** [comment]
Can you try to edit `media/2019-12-06_biggi_english.xml` and remove all occurences of `<![CDATA[` and `]]>`?

Maybe this helps. If so I will add another patch to bulk convert these files. Looks like I missed something in the backwards compatibility.

**Comment by joerg-nafcom** [comment]
that fixes it. i will do this with the German version of the entry too now

**Comment by joerg-nafcom** [comment]
manully re-generating the RSS feed fixed it there as well, thank you! :)

**Comment by emilengler** [comment]
Still have the issue on 3.0.1? Can't reproduce

**Comment by joerg-nafcom** [comment]
Yes, still have it in 3.0.1 

I still have some where I would have to delete <![CDATA[ manually out of it as you requested earlier, but we posted so many, I hope you fix it as you promised in an earlier reply with the next update

**Comment by emilengler** [comment]
Hi, some news to this issue!
Looks like I was a bit sloppy when creating 3.0 and forgot this point in the backwards compatible. I'm able to reproduce the issue and look forward to write the fix for it today.
I will also publish 3.0.2 somewhere this weekend or on Monday or Tuesday

Cheers,
Emil

**Comment by joerg-nafcom** [comment]
great news, but I don't sere the new release yet. is there a delay`?

**Comment by emilengler** [comment]
Hi Joerg,
there is indeed a delay.
Had a very busy week so I haven't managed to release PG 3.0.2 until the deadline.
Looking forward to do it this weekend

**Comment by emilengler** [comment]
Hi, I just published to patch for it!
I will now work on a way which will convert the old XML files to newer ones!
Thanks for the report

**Comment by joerg-nafcom** [comment]
how to download it? I still see no 3.0.2 a t https://podcastgenerator.github.io/download.html

**Comment by emilengler** [comment]
You're right, there is no 3.0.2 yet I only said that I fixed it.
Will see if I can manage it to release it tomorrow

**Comment by emilengler** [comment]
Hi sorry for this bad message but I can't give you a release date now. I have lots of stuff todo in the next weeks but still try to work on PG in the small amount of remaining free time
